# Generated by Django 5.1.5 on 2025-02-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_notification_payforothers_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
