# Generated by Django 5.1.5 on 2025-02-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_loanrequest_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='loan_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ledger.loanrequest'),
        ),
    ]
