# Generated by Django 5.1.5 on 2025-02-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_paymentdetail_loan_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
